{"name": "Login Authentication, Multiple paramters -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div/div[2]/nav/div[3]/h1\"}\n  (Session info: chrome=115.0.5790.171); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00EAA813+48355]\n\t(No symbol) [0x00E3C4B1]\n\t(No symbol) [0x00D45358]\n\t(No symbol) [0x00D709A5]\n\t(No symbol) [0x00D70B3B]\n\t(No symbol) [0x00D9E232]\n\t(No symbol) [0x00D8A784]\n\t(No symbol) [0x00D9C922]\n\t(No symbol) [0x00D8A536]\n\t(No symbol) [0x00D682DC]\n\t(No symbol) [0x00D693DD]\n\tGetHandleVerifier [0x0110AABD+2539405]\n\tGetHandleVerifier [0x0114A78F+2800735]\n\tGetHandleVerifier [0x0114456C+2775612]\n\tGetHandleVerifier [0x00F351E0+616112]\n\t(No symbol) [0x00E45F8C]\n\t(No symbol) [0x00E42328]\n\t(No symbol) [0x00E4240B]\n\t(No symbol) [0x00E34FF7]\n\tBaseThreadInitThunk [0x75EF7D59+25]\n\tRtlInitializeExceptionChain [0x770BB79B+107]\n\tRtlClearBits [0x770BB71F+191]\n\n", "trace": "  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\footersteps.py\", line 15, in step_impl\n    text = context.driver.find_element(By.XPATH,\"/html/body/div/div/div[2]/nav/div[3]/h1\").text\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Launch chrome browser", "status": "passed", "start": 1691758669456, "stop": 1691758671834}, {"name": "When Open login page", "status": "passed", "start": 1691758671836, "stop": 1691758673460}, {"name": "And Enter phone \"0208033578\" and pin \"1997\"", "status": "passed", "start": 1691758673460, "stop": 1691758674407}, {"name": "And Click on Enter", "status": "passed", "start": 1691758674409, "stop": 1691758674655}, {"name": "Then successful login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/div/div/div[2]/nav/div[3]/h1\"}\n  (Session info: chrome=115.0.5790.171); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00EAA813+48355]\n\t(No symbol) [0x00E3C4B1]\n\t(No symbol) [0x00D45358]\n\t(No symbol) [0x00D709A5]\n\t(No symbol) [0x00D70B3B]\n\t(No symbol) [0x00D9E232]\n\t(No symbol) [0x00D8A784]\n\t(No symbol) [0x00D9C922]\n\t(No symbol) [0x00D8A536]\n\t(No symbol) [0x00D682DC]\n\t(No symbol) [0x00D693DD]\n\tGetHandleVerifier [0x0110AABD+2539405]\n\tGetHandleVerifier [0x0114A78F+2800735]\n\tGetHandleVerifier [0x0114456C+2775612]\n\tGetHandleVerifier [0x00F351E0+616112]\n\t(No symbol) [0x00E45F8C]\n\t(No symbol) [0x00E42328]\n\t(No symbol) [0x00E4240B]\n\t(No symbol) [0x00E34FF7]\n\tBaseThreadInitThunk [0x75EF7D59+25]\n\tRtlInitializeExceptionChain [0x770BB79B+107]\n\tRtlClearBits [0x770BB71F+191]\n\n", "trace": "  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\footersteps.py\", line 15, in step_impl\n    text = context.driver.find_element(By.XPATH,\"/html/body/div/div/div[2]/nav/div[3]/h1\").text\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 740, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\innoson\\PycharmProjects\\test-oya\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1691758674656, "stop": 1691758674714}], "parameters": [{"name": "phone_number", "value": "0208033578"}, {"name": "pin", "value": "1997"}], "start": 1691758669453, "stop": 1691758674715, "uuid": "6cb409cf-5fa2-424c-98c4-a5538bef280d", "historyId": "9a3cf5555ea51954e24bfe3bec90fef2", "fullName": "Login: Login Authentication, Multiple paramters", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}